### ISSUE TITLE
Enumeration_Types package not in sync with the meta-models.

### ISSUE THREAD

**Issue by MicheleGuerriero** [dice-project/DICE-Profiles#10]
Some enumeration in the Enumaration_Types package are not updated with the respect to the DPIM metamodel. Few literals are now not there anymore or have been moved. @abelgomez @jmerse if you agree I could open a PR with a tentative fix.

**Comment by jmerse** [comment]
Yes, please proceed. But since we are also working with the Profiles (DDSM, etc.) please finish it asap.

**Comment by jmerse** [comment]
Ok. Merging PR #11
