### ISSUE TITLE
Clarifications on DTSM::Core::DiceData stereotype 

### ISSUE THREAD

**Issue by jmerse** [dice-project/DICE-Profiles#5]
Is `DTSM::Core::DiceData` really a Stereotype? Please provide  us with an example

**Comment by maelstromdat** [comment]
Ciao Abel, I've discussed with Michele and clarified this issue... The DiceData stereotype covers all the cases in which you specify various forms of data and perhaps want to perform QoD analysis on them - these are not specifically supported by DICE explicitly but the infrastructure we are providing should support them such that any said analysis is indeed possible (see req. PR2.7)... for example I may want to stereotype a certain type of data as DICE data and perform quality-of-data analysis, e.g., use a data de-duplication middleware. does that make sense? I would suggest to keep the stereotype and close the issue.

**Comment by jmerse** [comment]
Ok, we'll leave the DTSM::Core as initially designed as you suggest.

Closing the issue.
