### ISSUE TITLE
Nimbus and Supervisor do not extend any UML metaclass

### ISSUE THREAD

**Issue by jmerse** [dice-project/DICE-Profiles#6]
In `DTSM::Storm`, `Nimbus` and `Supervisor` do not extend any UML metaclass. Are they really stereotypes or should be just data types?

**Comment by abelgomez** [comment]
A new stereotype, `Zookeeper` has been added to fix issue #7 in commit c6c1016a65faa5b0507ce76b1dd85ed33d76cc09 that suffers from the same problem. If those stereotypes do no extend any metaclass, they are completely useless sin they cannot be used.

If they are used only to store some data but are not applied to any UML element should be converted into a complex datatype.

**Comment by maelstromdat** [comment]
Initially we considered them to be "instantiable" only by means of ad-hoc M2M transformations but given that this is no longer the case I would suggest we treat all these stereotypes as extending something fairly generic, e.g., _Classifier_ (but level-specific if needed). how does that sound?

**Comment by abelgomez** [comment]
Ok, we still don't envision the scenario in which those stereotypes could be used, but we will follow your advise and we keep them extending Classifier.

This has been addressed in commit d2f182e.
